### ISSUE TITLE
Add better open graph metadata

### ISSUE THREAD

**Issue by matthewmayer** [bangkokrb/rubyconfth#120]
Need to add an og:image so we don't always get a photo of Tim Riley's head

**Comment by matthewmayer** [comment]
i think it needs to be an absolute URL, facebook does not like it:

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Frubyconfth.com

<img width="1081" alt="Screenshot 2019-08-14 at 17 42 12" src="https://user-images.githubusercontent.com/152770/63015353-e2d03080-beba-11e9-918c-067d8c1725c2.png">

**Comment by olivierobert** [comment]
@matthewmayer It's already an absolute URL:

![image](https://user-images.githubusercontent.com/696529/63076603-f71a3900-bf5f-11e9-8b6e-d51f8427c28a.png)

But the results are cached. Therefore I invalidated the cache which removes the image URL warning:

![image](https://user-images.githubusercontent.com/696529/63076645-1ca74280-bf60-11e9-8cf5-c96b334fe177.png)

👉 https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Frubyconfth.com
