### ISSUE TITLE
As a user, I can find travel information

### ISSUE THREAD

**Issue by ditsara** [bangkokrb/rubyconfth#45]
Add content or links to content (may be on other websites such as TripAdvisor) pertaining to:

- Places to stay near the conference venue, or within easy accessibility
- Other interesting things to do in the area
- Other interesting things to do in Thailand
- How to get from the airport to the conference venue

**Comment by olivierobert** [comment]
@ditsara Good idea :-)

**Comment by abhinavmsra** [comment]
I can work on it. Do we have a already have a place on website for it?

**Comment by ditsara** [comment]
Not yet. I was thinking we could maybe add a separate section, to keep it separate from the main conference infomation (@olivierobert feel free to chime in). I think just some links to info should be fine.

- Places to stay (Google Maps link to hotels near Pullman King Power): https://www.google.com/maps/search/hotels+near+Victory+Monument,+Thanon+Phaya+Thai,+Ratchathewi,+Bangkok/@13.7599053,100.5342982,16z/data=!4m6!2m5!5m3!5m2!1s2019-09-06!2i2!6e3

- Interesting things to do in the area / in Thailand: maybe the appropriate tripadvisor page?

- How to get from the hotel: I could write something up for this -- Grab, ARL, regular taxi

**Comment by olivierobert** [comment]
Fixed in #82
