### ISSUE TITLE
Jittery scrolling on iOS Mobile Safari

### ISSUE THREAD

**Issue by matthewmayer** [bangkokrb/rubyconfth#50]
Start scrolling down the page
Expected: smooth scroll
Actual: jumps back to top

**Comment by matthewmayer** [comment]
Similar issue on Chrome on Android 8.0, any small upwards scroll will immediately snap to top.

**Comment by matthewmayer** [comment]
looks like the bug is in `rubyconfth/_js/components/AppNavigation/index.js` - is this a 3rd party component or something Nimble wrote @olivierobert

**Comment by olivierobert** [comment]
@matthewmayer custom UX/UI so custom component as usual at Nimble 😀 I will look into the issue

**Comment by olivierobert** [comment]
Fixed in #51
