### ISSUE TITLE
As a user, I can see contact email for sponshorship

### ISSUE THREAD

**Issue by abhinavmsra** [bangkokrb/rubyconfth#61]
Right now a potential sponsor would need to click on [I want to be a Sponshor](https://drive.google.com/file/d/1Js9G7xZBqq4plmyfufHwuHUm818vbE9s/view) link and then navigate all the way down to the last page of Sponsorship Deck file to get the contact email.

Can you add the contact email more prominently on the website itself? Something like

`Interested in sponsoring RubyConf TH 2019? Email us! [SPONSOR EMAIL]`

**Comment by olivierobert** [comment]
Fixed by #64
