### ISSUE TITLE
Speaker sponsor Saeloun

### ISSUE THREAD

**Issue by citizen428** [bangkokrb/rubyconfth#94]
Sponsoring: Vipul AM

![saeloun](https://user-images.githubusercontent.com/47985/60982459-b22f3100-a327-11e9-8eeb-953f49ee60e1.png)

URL: https://www.saeloun.com/

**Comment by olivierobert** [comment]
Can you ask them to add RubyConf TH to that page: https://www.saeloun.com/conferences.html ?

**Comment by citizen428** [comment]
Asked.
